const replacements: Array<[string, string]> = [
  ["同一口岸反馈提交过于频繁，请在10分钟后重试", "Reports for the same port are too frequent. Try again in 10 minutes."],
  ["仅运营人员可查看", "Only operators can view this page"],
  ["请切换身份", "Switch persona"],
  ["香港大学", "The University of Hong Kong"],
  ["香港国际机场", "Hong Kong International Airport"],
  ["深圳南山科技园", "Shenzhen Nanshan Technology Park"],
  ["深圳福田 CBD", "Shenzhen Futian CBD"],
  ["深圳福田CBD", "Shenzhen Futian CBD"],
  ["深圳北站", "Shenzhen North Station"],
  ["深圳宝安机场", "Shenzhen Bao'an International Airport"],
  ["深圳前海", "Shenzhen Qianhai"],
  ["九龙塘", "Kowloon Tong"],
  ["中环", "Central"],
  ["沙田", "Sha Tin"],
  ["香港 → 深圳", "Hong Kong → Shenzhen"],
  ["深圳 → 香港", "Shenzhen → Hong Kong"],
  ["罗湖", "Lo Wu"],
  ["福田", "Futian"],
  ["皇岗", "Huanggang"],
  ["深圳湾", "Shenzhen Bay"],
  ["莲塘", "Liantang"],
  ["文锦渡", "Man Kam To"],
  ["香港", "Hong Kong"],
  ["深圳", "Shenzhen"],
  ["口岸通关", " Port crossing"],
  ["口岸", " Port"],
  ["地铁", "Metro"],
  ["港铁", "MTR"],
  ["跨境巴士", "Cross-border coach"],
  ["巴士", "Bus"],
  ["物流", "Freight"],
  ["个人用户", "Personal user"],
  ["企业用户", "Enterprise user"],
  ["平台运营", "Platform Operations"],
  ["个人通勤", "Personal Mobility"],
  ["企业客户", "Enterprise Client"],
  ["运输调度", "Transport Dispatch"],
  ["口岸协调", "Port Coordination"],
  ["Demo 操作员", "Demo Operator"],
  ["个人通勤者", "Personal Commuter"],
  ["跨境通勤者", "Cross-border Commuter"],
  ["企业管理员", "Enterprise Administrator"],
  ["巴士调度员", "Coach Dispatcher"],
  ["物流调度员", "Freight Dispatcher"],
  ["口岸官方协调员", "Port Coordination Officer"],
  ["平台演示空间", "Platform Demo Workspace"],
  ["个人空间", "Personal Workspace"],
  ["湾区客运示例公司", "Greater Bay Coach Demo Company"],
  ["湾区物流示例公司", "Greater Bay Freight Demo Company"],
  ["口岸协调演示单位", "Port Coordination Demo Office"],
  ["晴朗", "Clear"],
  ["晴天", "Clear"],
  ["小雨", "Light rain"],
  ["降雨", "Rain"],
  ["雨天", "Rain"],
  ["暴雨", "Heavy rain"],
  ["雷暴", "Thunderstorm"],
  ["台风", "Typhoon"],
  ["普通工作日", "Normal weekday"],
  ["节假日高峰", "Holiday peak"],
  ["节假日", "Holiday"],
  ["大型演唱会散场", "Major concert release"],
  ["演唱会", "Concert"],
  ["恶劣天气", "Severe weather"],
  ["正常开放", "Open"],
  ["开放", "Open"],
  ["畅通", "Clear"],
  ["正常", "Moderate"],
  ["繁忙", "Busy"],
  ["非常繁忙", "Very busy"],
  ["拥挤", "Crowded"],
  ["低风险", "Low risk"],
  ["中风险", "Medium risk"],
  ["高风险", "High risk"],
  ["上升", "Rising"],
  ["回落", "Easing"],
  ["稳定", "Stable"],
  ["刚刚", "Just now"],
  ["分钟前", " minutes ago"],
  ["小时前", " hours ago"],
  ["现场通关反馈", "On-site crossing report"],
  ["人流较少", "Light passenger flow"],
  ["人流正常", "Moderate passenger flow"],
  ["人流较多", "Heavy passenger flow"],
  ["专用通道", "Dedicated channel"],
  ["旅客通道", "Passenger channel"],
  ["车辆通道", "Vehicle channel"],
  ["货运通道", "Freight channel"],
  ["时间匹配历史基线", "Time-matched historical baseline"],
  ["模拟天气影响", "Simulated weather impact"],
  ["节假日影响", "Holiday impact"],
  ["事件影响", "Event impact"],
  ["官方客流压力", "Official passenger-flow pressure"],
  ["官方拥堵等级", "Official congestion status"],
  ["众包反馈校准", "Crowd-report calibration"],
  ["双侧一致", "Cross-border sources agree"],
  ["双侧压力一致", "Cross-border pressure sources agree"],
  ["课堂 Demo", "classroom Demo"],
  ["课堂演示", "classroom Demo"],
  ["本地确定性演示", "Local deterministic Demo"],
  ["仅用于当前预测校准，不收集训练标签", "Used only for current forecast calibration; no training labels are collected"],
  ["不代表真实通关时间", "Not a live crossing-time measurement"],
  ["分钟", " minutes"],
  ["小时", " hours"],
  ["当前", "Current"],
  ["未来", "Future"],
  ["建议", "Recommendation"],
  ["预计", "Estimated"],
  ["等待", "wait"],
  ["压力", "pressure"],
  ["无", "None"],
];

const chinesePattern = /[\u3400-\u9fff]/;

export function englishDisplayText(value: string): string {
  let translated = value;
  for (const [source, target] of replacements) translated = translated.split(source).join(target);
  if (!chinesePattern.test(translated)) return translated;
  return translated.replace(/[\u3400-\u9fff]+/g, "").replace(/\s{2,}/g, " ").trim() || "Demo information";
}

export function localizeDemoPayload<T>(value: T, key = ""): T {
  if (typeof value === "string") return englishDisplayText(value) as T;
  if (Array.isArray(value)) {
    if (key === "affected_ports") return value;
    return value.map((item) => localizeDemoPayload(item, key)) as T;
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([entryKey, item]) => [entryKey, localizeDemoPayload(item, entryKey)]),
    ) as T;
  }
  return value;
}
